/* The following code was generated by JFlex 1.4.3 on 27/10/21, 2:35 p.�m. */

package compilador;
import java.util.ArrayList;
import java_cup.runtime.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 27/10/21, 2:35 p.�m. from the specification file
 * <tt>C:/Users/julia/Desktop/Practica1-Compiladores-master/Practica1-Compiladores-master/src/compilador/lexer.flex</tt>
 */
class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\4\1\4\2\0\1\4\22\0\1\10\5\0\1\14\1\7"+
    "\1\32\1\33\1\12\1\12\1\35\1\5\1\6\1\12\12\2\1\45"+
    "\1\34\1\13\1\11\1\13\2\0\5\1\1\46\2\1\1\47\6\1"+
    "\1\16\6\1\1\44\3\1\4\0\1\3\1\0\1\22\2\1\1\43"+
    "\1\42\1\30\1\21\1\41\1\26\2\1\1\31\1\23\1\27\1\20"+
    "\1\36\1\1\1\17\1\24\1\25\1\37\1\1\1\40\3\1\1\0"+
    "\1\15\uff83\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\1\1\6"+
    "\1\5\1\7\2\1\4\2\1\10\1\11\1\12\1\13"+
    "\5\2\1\14\1\2\2\0\1\15\1\7\3\2\1\16"+
    "\7\2\1\17\1\2\1\20\3\2\1\21\1\2\1\22"+
    "\11\2\1\23\10\2\1\24\3\2\1\25\1\26\1\27"+
    "\1\30\2\2\1\31\3\2\1\32\5\2\1\33\1\2"+
    "\1\0\1\2\1\34\1\2\1\35";

  private static int [] zzUnpackAction() {
    int [] result = new int[96];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\50\0\120\0\170\0\50\0\240\0\310\0\360"+
    "\0\50\0\360\0\u0118\0\u0140\0\u0168\0\u0190\0\u01b8\0\u01e0"+
    "\0\50\0\50\0\50\0\50\0\u0208\0\u0230\0\u0258\0\u0280"+
    "\0\u02a8\0\50\0\u02d0\0\u02f8\0\310\0\50\0\50\0\u0320"+
    "\0\u0348\0\u0370\0\120\0\u0398\0\u03c0\0\u03e8\0\u0410\0\u0438"+
    "\0\u0460\0\u0488\0\120\0\u04b0\0\u02f8\0\u04d8\0\u0500\0\u0528"+
    "\0\120\0\u0550\0\120\0\u0578\0\u05a0\0\u05c8\0\u05f0\0\u0618"+
    "\0\u0640\0\u0668\0\u0690\0\u06b8\0\120\0\u06e0\0\u0708\0\u0730"+
    "\0\u0758\0\u0780\0\u07a8\0\u07d0\0\u07f8\0\120\0\u0820\0\u0848"+
    "\0\u0870\0\120\0\120\0\120\0\120\0\u0898\0\u08c0\0\120"+
    "\0\u08e8\0\u0910\0\u0938\0\120\0\u0960\0\u0988\0\u09b0\0\u09d8"+
    "\0\u0a00\0\120\0\u0a28\0\u0a50\0\u0a78\0\u0aa0\0\u0ac8\0\120";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[96];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\2\1\5\1\6\1\2\1\7"+
    "\1\5\1\10\1\11\1\12\1\13\1\14\1\15\5\3"+
    "\1\16\1\3\1\17\1\3\1\20\1\3\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\27\1\3\1\30\1\31"+
    "\1\3\1\32\1\33\1\3\51\0\3\3\12\0\14\3"+
    "\4\0\7\3\1\0\2\3\2\0\1\4\3\0\1\34"+
    "\43\0\1\4\46\0\3\35\3\0\1\36\2\35\4\0"+
    "\14\35\4\0\7\35\1\0\2\35\11\0\1\37\52\0"+
    "\1\37\50\0\1\37\33\0\3\3\12\0\1\3\1\40"+
    "\12\3\4\0\7\3\1\0\2\3\1\0\3\3\12\0"+
    "\7\3\1\41\4\3\4\0\7\3\1\0\2\3\1\0"+
    "\3\3\12\0\11\3\1\42\1\43\1\3\4\0\7\3"+
    "\1\0\2\3\1\0\3\3\12\0\2\3\1\44\10\3"+
    "\1\45\4\0\7\3\1\0\2\3\1\0\3\3\12\0"+
    "\1\3\1\46\12\3\4\0\7\3\1\0\2\3\1\0"+
    "\3\3\12\0\11\3\1\47\2\3\4\0\7\3\1\0"+
    "\2\3\1\0\3\3\12\0\14\3\4\0\3\3\1\50"+
    "\3\3\1\0\2\3\1\0\3\3\12\0\11\3\1\51"+
    "\1\3\1\52\4\0\7\3\1\0\2\3\1\0\3\3"+
    "\12\0\2\3\1\53\11\3\4\0\7\3\1\0\2\3"+
    "\1\0\3\3\12\0\10\3\1\54\3\3\4\0\7\3"+
    "\1\0\2\3\2\0\1\55\46\0\3\3\12\0\2\3"+
    "\1\56\11\3\4\0\7\3\1\0\2\3\1\0\3\3"+
    "\12\0\1\3\1\57\12\3\4\0\4\3\1\60\2\3"+
    "\1\0\2\3\1\0\3\3\12\0\7\3\1\61\4\3"+
    "\4\0\1\62\6\3\1\0\2\3\1\0\3\3\12\0"+
    "\1\3\1\63\12\3\4\0\7\3\1\0\2\3\1\0"+
    "\3\3\12\0\2\3\1\64\11\3\4\0\7\3\1\0"+
    "\2\3\1\0\3\3\12\0\10\3\1\65\3\3\4\0"+
    "\7\3\1\0\2\3\1\0\3\3\12\0\7\3\1\66"+
    "\4\3\4\0\7\3\1\0\2\3\1\0\3\3\12\0"+
    "\10\3\1\67\3\3\4\0\7\3\1\0\2\3\1\0"+
    "\3\3\12\0\14\3\4\0\5\3\1\70\1\3\1\0"+
    "\2\3\1\0\3\3\12\0\6\3\1\71\5\3\4\0"+
    "\7\3\1\0\2\3\1\0\3\3\12\0\11\3\1\72"+
    "\2\3\4\0\7\3\1\0\2\3\1\0\3\3\12\0"+
    "\3\3\1\73\10\3\4\0\7\3\1\0\2\3\1\0"+
    "\3\3\12\0\10\3\1\74\3\3\4\0\7\3\1\0"+
    "\2\3\1\0\3\3\12\0\14\3\4\0\1\75\6\3"+
    "\1\0\2\3\1\0\3\3\12\0\14\3\4\0\1\3"+
    "\1\76\5\3\1\0\2\3\1\0\3\3\12\0\4\3"+
    "\1\77\7\3\4\0\7\3\1\0\2\3\1\0\3\3"+
    "\12\0\11\3\1\100\2\3\4\0\7\3\1\0\2\3"+
    "\1\0\3\3\12\0\10\3\1\101\3\3\4\0\7\3"+
    "\1\0\2\3\1\0\3\3\12\0\13\3\1\102\4\0"+
    "\7\3\1\0\2\3\1\0\3\3\12\0\14\3\4\0"+
    "\6\3\1\103\1\0\1\104\1\105\1\0\3\3\12\0"+
    "\14\3\4\0\4\3\1\106\2\3\1\0\2\3\1\0"+
    "\3\3\12\0\1\107\13\3\4\0\7\3\1\0\2\3"+
    "\1\0\3\3\12\0\1\3\1\110\12\3\4\0\7\3"+
    "\1\0\2\3\1\0\3\3\12\0\11\3\1\111\2\3"+
    "\4\0\7\3\1\0\2\3\1\0\3\3\12\0\7\3"+
    "\1\112\4\3\4\0\7\3\1\0\2\3\1\0\3\3"+
    "\12\0\7\3\1\61\4\3\4\0\7\3\1\0\2\3"+
    "\1\0\3\3\12\0\7\3\1\113\4\3\4\0\7\3"+
    "\1\0\2\3\1\0\3\3\12\0\13\3\1\114\4\0"+
    "\7\3\1\0\2\3\1\0\3\3\12\0\14\3\4\0"+
    "\4\3\1\115\2\3\1\0\2\3\1\0\3\3\12\0"+
    "\14\3\4\0\3\3\1\116\3\3\1\0\2\3\1\0"+
    "\3\3\12\0\2\3\1\117\11\3\4\0\7\3\1\0"+
    "\2\3\1\0\3\3\12\0\12\3\1\120\1\3\4\0"+
    "\7\3\1\0\2\3\1\0\3\3\12\0\1\3\1\121"+
    "\12\3\4\0\7\3\1\0\2\3\1\0\3\3\12\0"+
    "\4\3\1\122\7\3\4\0\7\3\1\0\2\3\1\0"+
    "\3\3\12\0\3\3\1\61\10\3\4\0\7\3\1\0"+
    "\2\3\1\0\3\3\12\0\10\3\1\123\3\3\4\0"+
    "\7\3\1\0\2\3\1\0\3\3\12\0\1\3\1\124"+
    "\12\3\4\0\7\3\1\0\2\3\1\0\3\3\12\0"+
    "\2\3\1\125\11\3\4\0\7\3\1\0\2\3\1\0"+
    "\3\3\12\0\5\3\1\126\6\3\4\0\7\3\1\0"+
    "\2\3\1\0\3\3\12\0\13\3\1\127\4\0\7\3"+
    "\1\0\2\3\1\0\3\3\12\0\3\3\1\130\10\3"+
    "\4\0\7\3\1\0\2\3\1\0\3\3\12\0\4\3"+
    "\1\131\7\3\4\0\7\3\1\0\2\3\1\0\3\3"+
    "\12\0\14\3\4\0\4\3\1\132\2\3\1\0\2\3"+
    "\1\0\3\3\12\0\1\3\1\133\12\3\4\0\7\3"+
    "\1\0\2\3\1\0\3\3\4\0\1\134\5\0\14\3"+
    "\4\0\7\3\1\0\2\3\1\0\3\3\12\0\4\3"+
    "\1\135\7\3\4\0\7\3\1\0\2\3\1\0\1\136"+
    "\14\0\14\136\4\0\7\136\1\0\2\136\1\0\3\3"+
    "\12\0\5\3\1\137\6\3\4\0\7\3\1\0\2\3"+
    "\1\0\3\136\12\0\14\136\4\0\7\136\1\0\2\136"+
    "\1\0\3\3\12\0\4\3\1\140\7\3\4\0\7\3"+
    "\1\0\2\3";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2800];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\3\1\1\11\7\1\4\11"+
    "\5\1\1\11\1\1\2\0\2\11\74\1\1\0\4\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[96];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */

public String errlex="";
public ArrayList<Token> ts = new ArrayList<Token>();
public Symbol symbol(int type){
    return new Symbol(type,yyline,yycolumn);

    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 124) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 27: 
          { ts.add(new Token("while fin ",yytext()));return symbol(sym.ew);
          }
        case 30: break;
        case 5: 
          { ts.add(new Token("Operador ",yytext()));return symbol(sym.op);
          }
        case 31: break;
        case 8: 
          { ts.add(new Token("p. izquierdo ",yytext()));return symbol(sym.pi);
          }
        case 32: break;
        case 21: 
          { ts.add(new Token("leer ",yytext()));return symbol(sym.rd);
          }
        case 33: break;
        case 13: 
          { ts.add(new Token("String ",yytext()));return symbol(sym.str);
          }
        case 34: break;
        case 16: 
          { ts.add(new Token("Decimal ",yytext()));return symbol(sym.floatNum);
          }
        case 35: break;
        case 6: 
          { ts.add(new Token("asignacion ",yytext()));return symbol(sym.ig);
          }
        case 36: break;
        case 22: 
          { ts.add(new Token("escribir ",yytext()));return symbol(sym.wt);
          }
        case 37: break;
        case 20: 
          { ts.add(new Token("else ",yytext()));return symbol(sym.el);
          }
        case 38: break;
        case 9: 
          { ts.add(new Token("p. derecho ",yytext()));return symbol(sym.pd);
          }
        case 39: break;
        case 15: 
          { ts.add(new Token("while condicion ",yytext()));return symbol(sym.doAction);
          }
        case 40: break;
        case 25: 
          { ts.add(new Token("if fin ",yytext()));return symbol(sym.ei);
          }
        case 41: break;
        case 17: 
          { ts.add(new Token("Tipo de dato ",yytext()));return symbol(sym.tp);
          }
        case 42: break;
        case 1: 
          { errlex+=("\n Error Lexico, en linea : "+ (yyline+1)+" , "+(yycolumn+1)+ "caracter no valido "+yytext());
          }
        case 43: break;
        case 7: 
          { ts.add(new Token("Logicos ",yytext()));return symbol(sym.log);
          }
        case 44: break;
        case 11: 
          { ts.add(new Token("coma ",yytext()));return symbol(sym.com);
          }
        case 45: break;
        case 24: 
          { ts.add(new Token("while inicio ",yytext()));return symbol(sym.wh);
          }
        case 46: break;
        case 23: 
          { ts.add(new Token("for condicion ",yytext()));return symbol(sym.ul);
          }
        case 47: break;
        case 12: 
          { ts.add(new Token("Inicio for ",yytext()));return symbol(sym.colon);
          }
        case 48: break;
        case 18: 
          { ts.add(new Token("for inicio ",yytext()));return symbol(sym.fr);
          }
        case 49: break;
        case 28: 
          { ts.add(new Token("Definicion programa ",yytext()));return symbol(sym.ip);
          }
        case 50: break;
        case 19: 
          { ts.add(new Token("Paso ",yytext()));return symbol(sym.step);
          }
        case 51: break;
        case 2: 
          { ts.add(new Token("Variable ",yytext()));return symbol(sym.var);
          }
        case 52: break;
        case 3: 
          { ts.add(new Token("Entero ",yytext()));return symbol(sym.integer);
          }
        case 53: break;
        case 29: 
          { ts.add(new Token("Fin del programa",yytext()));return symbol(sym.fp);
          }
        case 54: break;
        case 26: 
          { ts.add(new Token("for fin ",yytext()));return symbol(sym.ef);
          }
        case 55: break;
        case 4: 
          { 
          }
        case 56: break;
        case 10: 
          { ts.add(new Token("punto y coma ",yytext()));return symbol(sym.pc);
          }
        case 57: break;
        case 14: 
          { ts.add(new Token("if inicio ",yytext()));return symbol(sym.ifCond);
          }
        case 58: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
