package compilador;

//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Oct 27 14:40:04 COT 2021
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int pc = 4;
  public static final int wt = 8;
  public static final int el = 16;
  public static final int tp = 26;
  public static final int ei = 17;
  public static final int ef = 14;
  public static final int com = 6;
  public static final int step = 27;
  public static final int fr = 12;
  public static final int wh = 9;
  public static final int fp = 25;
  public static final int log = 23;
  public static final int ip = 24;
  public static final int op = 22;
  public static final int doAction = 10;
  public static final int ifCond = 15;
  public static final int ul = 13;
  public static final int ig = 5;
  public static final int EOF = 0;
  public static final int str = 20;
  public static final int rd = 7;
  public static final int error = 1;
  public static final int integer = 18;
  public static final int colon = 28;
  public static final int ew = 11;
  public static final int var = 21;
  public static final int floatNum = 19;
  public static final int pi = 2;
  public static final int pd = 3;
}

